image: ghcr.io/epics-containers/gateways-developer:2024.12.3

# nodeName: # if set, the pod will be scheduled on this node
overrideConfig: true

# this Gatewat will use EPICS_CA_SERVERS_LIST to get to indivual IOCs
# # broadcast on controls dev network
# caAddrList: 172.23.255.255
# pvaAddrList: 172.23.255.255

caServerPort: 9064
pvaServerPort: 9065

hostNetwork: false
