# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.4.2/ioc-instance.schema.json

# shared values for all services
global:
  ioc_group: hgv27681
  location: hgv27681
  enabled: true

ioc-instance:
  # personal namespaces are not authorized to use hostNetwork=true
  hostNetwork: false
