apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      # When running inside the container network, we need full access service
      # account to query the namespace for IOCs to add to EPICS_CA_ADDR_LIST
      {{- if .Values.hostNetwork }}
      serviceAccountName: default-full-access-mounted
      {{- end }}
      # if overrideConfig is set, mount the config map over the default
      # config files supplied inside the container image
      {{- if .Values.overrideConfig }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-ca-gateway
          command:
           - bash
          args:
           - "/config/start-ca.sh"
          env:
            # set this to YES for network host or NO for cluster network
            # this controls wether the gateway will use ADDR_LIST of internal
            # addresses, or use the ADDR_LIST below
            - name: HOST_NETWORK
              value: {{ ternary "YES" "NO" .Values.hostNetwork | quote}}
            - name: EPICS_CA_AUTO_ADDR_LIST
              value: "NO"
            - name: EPICS_CA_ADDR_LIST
              value: {{ .Values.caAddrList }}
            - name: CA_SERVER_PORT
              value:  {{ .Values.caServerPort | quote }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 1500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          stdin: true
          tty: true
          {{- if .Values.overrideConfig }}
          volumeMounts:
          - name: config-volume
            mountPath: /config
          {{- end }}

        - name: "{{ .Release.Name }}-pva-gateway"
          command:
           - bash
          args:
           - "/config/start-pva.sh"
          env:
            - name: HOST_NETWORK
              value: {{ ternary "YES" "NO" .Values.hostNetwork | quote }}
            - name: EPICS_PVA_AUTO_ADDR_LIST
              value: "NO"
            - name: EPICS_PVA_ADDR_LIST
              value: {{ .Values.pvaAddrList }}
            - name: PVA_SERVER_PORT
              value:  {{ .Values.pvaServerPort | quote }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 1500Mi
            requests:
              cpu: 200m
              memory: 400Mi
          stdin: true
          tty: true
          {{- if .Values.overrideConfig }}
          volumeMounts:
          - name: config-volume
            mountPath: /config
          {{- end }}

      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork | default "false" }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 1

