# When using host network IOCs are addressed directly by host IP
# If using cluster network, the CA gateway will discover IOCs
# and we use a service to keep the IP stable
{{- if not .Values.hostNetwork }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    location: {{ .Values.global.location }}
    ioc_group: {{ .Values.global.ioc_group }}
    is_ioc: "true"
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    # CA server port
    - protocol: TCP
      port: 5064
      targetPort: 5064
      name: ca-server
    # CA repeater port
    - protocol: TCP
      port: 5065
      targetPort: 5065
      name: ca-repeater
    # PVA server port
      port: 5075
      targetPort: 5075
      name: pva-server
{{- end }}